### ISSUE TITLE
Add more starter styles

### ISSUE THREAD

**Issue by SteveBarnett** [SteveBarnett/fufu#2]
- `:target` placeholder styles
- button placeholder styles
- skip link styles
## Buttons

``` css
button:hover, button:focus {
    /* make it look like you can press it */
}
```

If the button is square, you can improve the visibility of the :hover and :focus states using a thicker, solid outline. Otherwise, a change in background-color can help.

---

``` css
button {
    outline: 2px solid transparent;
    outline-offset: 100px;
    transition: 0.5s all ease;
}
```

Then we just need to tighten the net while simultaneously making the outline visible.

``` css
button:focus {
    outline: 2px solid #000;
    outline-offset: 0;
}
```

---

``` css
button:active {
    position: relative;
    top: 3px; /* 3px drop */
    box-shadow: 0 0 0 #222; /* less by 3px (to zero) */
}
```

---

``` css
[disabled], a:not([href]) {
    /* styles for any element that takes a disabled attribute or links that do not have the href attribute present */
}
```

---

``` css
button:active, button[aria-pressed="true"]
```
## skip link

Hide it, then show it on focus. 

``` css
a.skip {
    position: relative;
    top: -100px;
    transition: position 0.5s ease;
}

a.skip:focus {
    top: 0;
}
```
