### ISSUE TITLE
Add long word handling

### ISSUE THREAD

**Issue by SteveBarnett** [SteveBarnett/fufu#29]
``` css
.hyphenate {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

https://justmarkup.com/log/2015/07/31/dealing-with-long-words-in-css/
