### ISSUE TITLE
Add system font stack

### ISSUE THREAD

**Issue by SteveBarnett** [SteveBarnett/fufu#43]
``` css
body {  
   font-family: -apple-system, 
                BlinkMacSystemFont, 
                "Segoe UI", 
                Roboto,
                "Droid Sans",
                Ubuntu, 
                sans-serif;
}
```
